### ISSUE TITLE
Port to TelepathyGLib

### ISSUE THREAD

**Issue by quozl** [sugarlabs/collabwrapper#1]
collabwrapper.py is used by several activities.

**Comment by chimosky** [comment]
@quozl, what other work needs to be done?

**Comment by quozl** [comment]
@chimosky, make it work.  See https://github.com/sugarlabs/collabwrapper/pull/4 for how it failed.

**Comment by chimosky** [comment]
@quozl, I'll do more testing once i get rdesktop up and running - migrating to another os -.

**Comment by quozl** [comment]
Test case;
* set up two instances of Sugar and confirm the buddy icon of each instance is visible in the other instance Neighbourhood view,
* install the CollabWrapperTest activity on both instances,
* run the activity on one instance, then share the activity,
* verify the other instance shows the activity on the Neighbourhood view,
* join the shared activity,
* communicate between the two.
