### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/collabwrapper#11]
* [x] complete https://github.com/sugarlabs/collabwrapper/issues/1,
* [x] cherry-pick patches to CollabWrapper from the [Browse activity `python3` branch](https://github.com/sugarlabs/browse-activity/tree/python3), and;
* [x] port CollabWrapper to Python 3,
* [x] port CollabWrapper test activity to Python 3,
* [x] make pull request.

**Comment by Aniket21mathur** [comment]
The [Port to Python 3](https://github.com/sugarlabs/browse-activity/commit/5810694b3b22f15da73d169058cf39e93b4a1052) commit of the browser activity do not include any changes to `collabwrapper.py` changes are introduced by `pep` and `flake` fixes.

Though after `TelepathyGLib` port collabwrapper has changed considerably, cherry-picking commits from Browser will lead to a number of conflicts and will not be of any help.

So, I don't think cherry-picking from browser is a good idea.

Thanks!

**Comment by Aniket21mathur** [comment]
I tested collabwrapper at https://github.com/sugarlabs/collabwrapper/commit/758e77c3580cace1e5669383d7d005db37fb3798 with `2to3`. I don't find any changes required for Python 3 port.

**Comment by quozl** [comment]
Thanks.  Updated opening comment checklist.

**Comment by Aniket21mathur** [comment]
Any need to keep this issue open?

**Comment by quozl** [comment]
Someone forgot a "Fixes".

**Comment by Aniket21mathur** [comment]
I did included it in https://github.com/sugarlabs/collabwrapper/pull/18/commits/6169fd425e44ecb63eee0eef97d4f02da0f8a839, please see.

The issue was still open, strange!

**Comment by quozl** [comment]
The commits were squashed.

**Comment by quozl** [comment]
i.e. the pull request didn't have a fixes, one of the commits in the change set did, but that commit description was not kept when I merged.

**Comment by Aniket21mathur** [comment]
Ohh! Thanks for explaining. :-)
I will include "Fixes" in a comment on the pr from next time.
