### ISSUE TITLE
Test activity icon is invisible

### ISSUE THREAD

**Issue by quozl** [sugarlabs/collabwrapper#12]
The icon is white, and does not show up in the activity ring, and is likewise invisible against the neighbourhood view.

Workaround is to hover over the gap in the home view ring, or the area just below the child icon on the neighbourhood view.

**Comment by Aniket21mathur** [comment]
@quozl  I am not able to understand the issue. Please help.
Thanks

**Comment by quozl** [comment]
Please be more specific?  Or tell me what you think?

**Comment by quozl** [comment]
https://github.com/sugarlabs/sugariconify was used, fixed in 2928eb0.
